codecov:
  require_ci_to_pass: yes

comment:
  layout: "diff, files"           # Only show coverage diff
  require_changes: true  # Only post comment if coverage change
  behavior: default      # Update, if exists. Otherwise post new
  branches: master

coverage:
  range: 75...90        
  precision: 2
  round: down

  status:
    project:
      default: false
#      default:
#        # basic
#        target: auto
#        threshold: null
#        base: auto 
#        # advanced
#        branches: null
#        if_no_uploads: error
#        if_not_found: success
#        if_ci_failed: error
#        only_pulls: false
#        flags: null
#        paths: null
    patch:
      default: false
#      default:
#        # basic
#        target: auto
#        threshold: null
#        base: auto 
#        # advanced
#        branches: null
#        if_no_uploads: error
#        if_not_found: success
#        if_ci_failed: error
#        only_pulls: false
#        flags: null
#        paths: null

ignore:
  - devtools/.*
  - doc/.*
  - example/.*
  - pkg-config/.*
  - src/jsonctestrunner/.*
  - src/test_lib_json/.*
  - test/.*

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

