codecov:
  require_ci_to_pass: yes

comment:
  layout: "diff, files"           # Only show coverage diff
  require_changes: true  # Only post comment if coverage change
  behavior: default      # Update, if exists. Otherwise post new
  branches: master
  
coverage:
  range: 75...90        
  precision: 2
  round: down

  status:
    project: yes
    patch: yes
    changes: no
    
ignore:
  - example/.*
  - devtool/.*
  - doc/.*
  - pkg-config/.*

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

