comment:
  layout: diff           # Only show coverage diff
  require_changes: true  # Only post comment if coverage change
  behavior: default      # Update, if exists. Otherwise post new
  
  
coverage:
  range: 75...90        
  precision: 2
  round: down

  ignore:
  - example/.*
  - devtool/.*
  - doc/.*
  - pkg-config/.*

  status:
    project:
      default:
        target: auto
        if_no_uploads: error
    
    patch:
      default:
        target: auto
        if_no_uploads: error

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
      method: no
      macro: no

