comment:
  layout: header, header, diff
  
coverage:
  precision: 2
  round: nearest

  ignore:
  - example/.*
  - devtool/.*
  - doc/.*
  - pkg-config/.*

  status:
    project:
      default:
        target: auto
        if_no_uploads: error
    
    patch:
      default:
        if_no_uploads: error

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: yes
      method: no
      macro: no

