comment:
  layout: header, changes, diff
  
coverage:
  precision: 2
  round: nearest
  range: "75...90"
  bot: codecov-bot
  ignore:
  - devtool/.*
  - doc/.*
  - example/.*
  - pkg-config/.*

  status:
    project: no
    patch: no
    changes: no

  parsers:
    gcov:
      branch_detection:
        macro: no
        loop: no
        conditional: no
        method: no
