codecov:
  require_ci_to_pass: yes
  bot: codecov-bot

comment:
  layout: header, diff
  behavior: default
  require_changes: yes
  
coverage:
  precision: 2
  round: nearest
  range: "75...90"
  ignore:
  - devtool/.*
  - doc/.*
  - example/.*
  - pkg-config/.*

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

