comment:
  layout: header, changes, diff
  
coverage:
  precision: 2
  round: nearest
  range: "75...95"
  bot: codecov-bot
  ignore:
  - devtool/.*
  - doc/.*
  - example/.*
  - pkg-config/.*

  status:
    project:
      default:
        target: auto
        if_no_uploads: error

    patch:
      default:
        if_no_uploads: error

    changes: true

  parsers:
    gcov:
      branch_detection:
        macro: no
        loop: no
        conditional: no
        method: no
